#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
cat <<!
 ___  ___  ___ _    _
|   \| _ )/ __| |  (_)_ _ _  ___ __
| |) | _ \ (_ | |__| | ' \ || \ \ /
|___/|___/\___|____|_|_||_\_,_/_\_\

~matteyeux
!
exec /bin/sh
